import Head from 'next/head'

export default function CarHyundai() {
  return (
    <div>
      <Head>
        <title>Car</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
      <div class="container">
      <h3 class="title">Hyundai Elantra 2.0</h3>
          <img class="image" src="https://mobistatic3.focus.bg/mobile/photosmob/361/1/big1/11672766563582361_T.jpg"/>
          <div class="desc">
            <p id="name">Hyundai Elantra</p>
            <p id="price">39 999лв</p>  
              <ul class="specs">
                <li>Дата на производство : <p id="year"> януари 2021г.</p></li>
                <li>Тип двигател: <p id="engine">Бензинов</p></li> 
                <li>Мощност: <p id="horsepower">152кс</p></li> 
                <li>Евростандарт: <p id="eco">Евро 6</p></li> 
                <li>Скоростна кути: <p id="trans">Автоматична</p></li>
                <li>Пробег: <p id="millage">1162 км</p></li>
                <li>Цвят: <p id="color">Тъмно Сив</p></li>
              </ul>
            </div>
          </div>
      </main>
    </div>
  )
}
