import Head from 'next/head'

export default function CarM4() {
  return (
    <div>
      <Head>
        <title>Car</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
      <div class="container">
        <h3 class="title">BMW M4 *Head-up*Pano*Harman Kardon</h3>
          <img class="image" src="https://mobistatic4.focus.bg/mobile/photosmob/354/1/big1/11662725891193354_9l.jpg"/>
          <div class="desc">
            <p id="name">BMW M4</p>
            <p id="price">89 200лв</p>      
              <ul class="specs">
                <li>Дата на производство : <p id="year"> Октомври 2016</p></li>
                <li>Тип двигател: <p id="engine">Бензинов</p></li> 
                <li>Мощност: <p id="horsepower">431кс</p></li> 
                <li>Евростандарт: <p id="eco">Евро 6</p></li> 
                <li>Скоростна кути: <p id="trans">Автоматична</p></li>
                <li>Пробег: <p id="millage">1033300 км</p></li>
                <li>Цвят: <p id="color">Син</p></li>
              </ul>
            </div>
          </div>
      </main>
    </div>
  )
}
