import Head from 'next/head'
import {Navigation, Pagination, Scrollbar, A11y} from "swiper"
import {Swiper, SwiperSlide} from "swiper/react";


export default function CarVw() {
    const images = [
        "https://mobistatic4.focus.bg/mobile/photosmob/354/1/big1/11662725891193354_9l.jpg",
        "https://mobistatic4.focus.bg/mobile/photosmob/354/1/big1/11662725891193354_UI.jpg", 
        "https://mobistatic4.focus.bg/mobile/photosmob/354/1/big1/11662725891193354_RS.jpg",
        "https://mobistatic4.focus.bg/mobile/photosmob/354/1/big1/11662725891193354_1u.jpg"
      ];
  return (
    <div>
      <Head>
        <title>Car</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <div className="carousel-container">
        <Swiper
          modules={[Navigation, Pagination, Scrollbar, A11y]}
          className="external-buttons"
          spaceBetween={24}
          slidesPerView={1}
          navigation
          updateOnWindowResize
          observer
          observerParents
          initialSlide={1}
          loop
        >
          {images.map((image, index) => (
            <SwiperSlide key={index}>
              <img
                height="200"
                width="300"
                alt="img"
                className="image"
                src={image}
              />
            </SwiperSlide>
          ))}
        </Swiper>
      </div>
      <div class="container">
      <h3 class="title">VW Beetle 2.0TSI Final Edition </h3>
          <img class="image" src="https://mobistatic1.focus.bg/mobile/photosmob/703/1/big1/11687953711836703_bO.jpg"/>
          <div class="desc">
            <p id="name">VW  Beetle 2.0TSI</p>
            <p id="price">49 999лв</p>  
              <ul class="specs">
                <li>Дата на производство : <p id="year"> октомври 2019г.</p></li>
                <li>Тип двигател: <p id="engine">Бензинов</p></li> 
                <li>Мощност: <p id="horsepower">220кс</p></li> 
                <li>Евростандарт: <p id="eco">Евро 6</p></li> 
                <li>Скоростна кути: <p id="trans">Автоматична</p></li>
                <li>Пробег: <p id="millage">16000 км</p></li>
                <li>Цвят: <p id="color">Бежов</p></li>
              </ul>
            </div>
          </div>
      </main>
    </div>
  )
}
